
import Books.BookAction;
import Books.Books;

import com.google.zxing.qrcode.encoder.QRCode;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Admin extends javax.swing.JFrame {
     
     QR_ qr= new QR_();
    
   public static int bookid;
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfbookid = new javax.swing.JTextField();
        tfauthor = new javax.swing.JTextField();
        tfbookname = new javax.swing.JTextField();
        tfpublisher = new javax.swing.JTextField();
        tfyearofpublication = new javax.swing.JTextField();
        addBook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lb_pic = new javax.swing.JLabel();
        bt_seeQr = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bt_deleteUser = new javax.swing.JButton();
        bt_deleteBook = new javax.swing.JButton();
        lb_addbook = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 74, 45));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Author:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 192, 74, 45));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Year of Publications:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 294, 153, 45));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 141, 74, 45));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Publisher:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 243, 74, 45));

        tfbookid.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.add(tfbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 102, 152, -1));

        tfauthor.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.add(tfauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 204, 152, -1));

        tfbookname.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.add(tfbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 153, 152, -1));

        tfpublisher.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.add(tfpublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 255, 152, -1));

        tfyearofpublication.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.add(tfyearofpublication, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 306, 152, -1));

        addBook.setBackground(new java.awt.Color(255, 255, 255));
        addBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBook.setForeground(new java.awt.Color(102, 0, 102));
        addBook.setText("Add Book to Library");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });
        jPanel1.add(addBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 345, 206, 56));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Add More Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 470, -1, -1));
        jPanel1.add(lb_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 300, 300));

        bt_seeQr.setBackground(new java.awt.Color(255, 255, 255));
        bt_seeQr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_seeQr.setForeground(new java.awt.Color(102, 0, 102));
        bt_seeQr.setText("See the QR Code");
        bt_seeQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seeQrActionPerformed(evt);
            }
        });
        jPanel1.add(bt_seeQr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 361, -1, -1));

        jLabel7.setBackground(new java.awt.Color(102, 0, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADMINISTER ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 385, 73));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 501, -1, -1));

        bt_deleteUser.setBackground(new java.awt.Color(255, 255, 255));
        bt_deleteUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_deleteUser.setForeground(new java.awt.Color(102, 0, 102));
        bt_deleteUser.setText("Delete the User");
        bt_deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteUserActionPerformed(evt);
            }
        });
        jPanel1.add(bt_deleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 532, 143, -1));

        bt_deleteBook.setBackground(new java.awt.Color(255, 255, 255));
        bt_deleteBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_deleteBook.setForeground(new java.awt.Color(102, 0, 102));
        bt_deleteBook.setText("Delete the Book");
        bt_deleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteBookActionPerformed(evt);
            }
        });
        jPanel1.add(bt_deleteBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 501, -1, -1));

        lb_addbook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_addbook.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_addbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 419, 305, 31));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ab05346be26055336b96d308c4a81f90.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
       int  year;
       String bookname, author, publisher;
       
       bookid= Integer.parseInt(tfbookid.getText());
       year= Integer.parseInt(tfyearofpublication.getText());
       
       bookname= tfbookname.getText();
       author= tfauthor.getText();
       publisher= tfpublisher.getText();
       
       Books book= new Books(  bookid,bookname,author, publisher, year);
       BookAction.book.add(book);
       
      QR_.mainCaller();
      
       lb_addbook.setText("Book has been added!");  
    
    }//GEN-LAST:event_addBookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.setVisible(false);
     new Admin().setVisible(true);
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_seeQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seeQrActionPerformed
       
        String s="C:\\Users\\Nova Stark\\OneDrive\\Belgeler\\NetBeansProjects\\Ceng201 Project\\src\\Images\\ID_"+bookid;
	String qr = s+"_QR.png";
        ImageIcon iconLogo = new ImageIcon(qr);
       lb_pic.setIcon(iconLogo);
    }//GEN-LAST:event_bt_seeQrActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     this.setVisible(false);
     new Login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bt_deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteUserActionPerformed
        new DeleteUser().setVisible(true);
    }//GEN-LAST:event_bt_deleteUserActionPerformed

    private void bt_deleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteBookActionPerformed
        new DeleteBook().setVisible(true);
    }//GEN-LAST:event_bt_deleteBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JButton bt_deleteBook;
    private javax.swing.JButton bt_deleteUser;
    private javax.swing.JButton bt_seeQr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_addbook;
    private javax.swing.JLabel lb_pic;
    private javax.swing.JTextField tfauthor;
    private javax.swing.JTextField tfbookid;
    private javax.swing.JTextField tfbookname;
    private javax.swing.JTextField tfpublisher;
    private javax.swing.JTextField tfyearofpublication;
    // End of variables declaration//GEN-END:variables
}
