
import Books.Books;
import Books.BookAction;

import User.Academician;
import User.Student;
import User.User;
import com.github.sarxos.webcam.Webcam;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.text.*;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */

public class LibraryPanel extends javax.swing.JFrame {
        public static String  s;
  
         
       public static String book( int bookId, String bookName, String author, String publisher, int yearOfPublication)
     {
       String bookInfo= ""+ bookId+ bookName+ author+ publisher+ yearOfPublication;
        return bookInfo;
       }
     
    
     BookAction bookAction= new BookAction();
     
    
    /**
     * Creates new form LibraryPanel
     */
    
    public LibraryPanel() {
        
        initComponents();
        
        if (User.searchUser(User.currentId) instanceof Student) {
            ta_displayuserinfo.append(Student.searchUser(User.currentId).toString());
        }
        else if (User.searchUser(User.currentId) instanceof Academician) {
             ta_displayuserinfo.append(Academician.searchUser(User.currentId).toString());
        }
        
       
        allBooks.setVisible(false); 
        removingBook.setVisible(false);
        panel_view.setVisible(false);
          
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        allBooks = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchedId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchedBookInfo = new javax.swing.JTextArea();
        addToUser = new javax.swing.JButton();
        message1 = new javax.swing.JLabel();
        jbSearch = new javax.swing.JButton();
        message3 = new javax.swing.JLabel();
        message4 = new javax.swing.JLabel();
        lbSearch = new javax.swing.JLabel();
        CloseGet = new javax.swing.JButton();
        remember = new javax.swing.JLabel();
        panel_view = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_displayAllBooks = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        bt_sorting = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_alphSorting = new javax.swing.JTextArea();
        CloseView = new javax.swing.JButton();
        removingBook = new javax.swing.JPanel();
        bt_displayMyBooks = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_displayMyBook = new javax.swing.JTable();
        message2 = new javax.swing.JLabel();
        bt_return = new javax.swing.JButton();
        CloseReturn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_displayuserinfo = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbAddBook = new javax.swing.JButton();
        jbRemoveBook = new javax.swing.JButton();
        jbViewBooks = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libray Automation System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LIBRARY AUTOMATION SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        allBooks.setBackground(new java.awt.Color(235, 213, 255));
        allBooks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        allBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Search Book (Enter ID):");
        allBooks.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 20));
        allBooks.add(searchedId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 119, -1));

        searchedBookInfo.setColumns(20);
        searchedBookInfo.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        searchedBookInfo.setForeground(new java.awt.Color(51, 0, 51));
        searchedBookInfo.setRows(5);
        searchedBookInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jScrollPane1.setViewportView(searchedBookInfo);

        allBooks.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 180));

        addToUser.setBackground(new java.awt.Color(255, 255, 255));
        addToUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addToUser.setForeground(new java.awt.Color(51, 0, 51));
        addToUser.setText("Add Book");
        addToUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToUserActionPerformed(evt);
            }
        });
        allBooks.add(addToUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 100, -1));

        message1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        message1.setForeground(new java.awt.Color(51, 0, 51));
        allBooks.add(message1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 160, 64));

        jbSearch.setBackground(new java.awt.Color(255, 255, 255));
        jbSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbSearch.setForeground(new java.awt.Color(51, 0, 51));
        jbSearch.setText("Search");
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });
        allBooks.add(jbSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 119, -1));

        message3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        message3.setForeground(new java.awt.Color(51, 0, 51));
        allBooks.add(message3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, 30));

        message4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        message4.setForeground(new java.awt.Color(51, 0, 51));
        allBooks.add(message4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 190, 37));

        lbSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        allBooks.add(lbSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 80, 80));

        CloseGet.setBackground(new java.awt.Color(255, 255, 255));
        CloseGet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CloseGet.setForeground(new java.awt.Color(51, 0, 51));
        CloseGet.setText("Close");
        CloseGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseGetActionPerformed(evt);
            }
        });
        allBooks.add(CloseGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        remember.setBackground(new java.awt.Color(255, 255, 255));
        remember.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        remember.setForeground(new java.awt.Color(51, 0, 51));
        allBooks.add(remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 290, 20));

        jPanel1.add(allBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 390, 350));

        panel_view.setBackground(new java.awt.Color(235, 213, 255));
        panel_view.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panel_view.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_displayAllBooks.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        table_displayAllBooks.setForeground(new java.awt.Color(51, 0, 51));
        table_displayAllBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book Id", "Book Name", "Author", "Publisher", "Year of Publication"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_displayAllBooks);

        panel_view.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("LIBRARY");
        panel_view.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 136, 31));

        bt_sorting.setBackground(new java.awt.Color(255, 255, 255));
        bt_sorting.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_sorting.setForeground(new java.awt.Color(51, 0, 51));
        bt_sorting.setText("Sorting");
        bt_sorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sortingActionPerformed(evt);
            }
        });
        panel_view.add(bt_sorting, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        ta_alphSorting.setColumns(20);
        ta_alphSorting.setRows(5);
        ta_alphSorting.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jScrollPane5.setViewportView(ta_alphSorting);

        panel_view.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 340, 110));

        CloseView.setBackground(new java.awt.Color(255, 255, 255));
        CloseView.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CloseView.setForeground(new java.awt.Color(51, 0, 51));
        CloseView.setText("Close");
        CloseView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseViewActionPerformed(evt);
            }
        });
        panel_view.add(CloseView, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jPanel1.add(panel_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 370, 350));

        removingBook.setBackground(new java.awt.Color(235, 213, 255));
        removingBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        removingBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_displayMyBooks.setBackground(new java.awt.Color(255, 255, 255));
        bt_displayMyBooks.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_displayMyBooks.setForeground(new java.awt.Color(51, 0, 51));
        bt_displayMyBooks.setText("My Books");
        bt_displayMyBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_displayMyBooksActionPerformed(evt);
            }
        });
        removingBook.add(bt_displayMyBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        table_displayMyBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        table_displayMyBook.setForeground(new java.awt.Color(51, 0, 51));
        table_displayMyBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book Id", "Book Name", "Author", "Publisher", "Year Of Publication"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_displayMyBook);

        removingBook.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 100));
        removingBook.add(message2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 190, 60));

        bt_return.setBackground(new java.awt.Color(255, 255, 255));
        bt_return.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_return.setForeground(new java.awt.Color(51, 0, 51));
        bt_return.setText("Read QR Code");
        bt_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_returnActionPerformed(evt);
            }
        });
        removingBook.add(bt_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, -1));

        CloseReturn.setBackground(new java.awt.Color(255, 255, 255));
        CloseReturn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CloseReturn.setForeground(new java.awt.Color(51, 0, 51));
        CloseReturn.setText("Close");
        CloseReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseReturnActionPerformed(evt);
            }
        });
        removingBook.add(CloseReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 70, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 51));
        jButton2.setText("Return The Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        removingBook.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 150, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookReturn.png"))); // NOI18N
        removingBook.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, 80));

        jPanel1.add(removingBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 370, 350));

        ta_displayuserinfo.setColumns(20);
        ta_displayuserinfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ta_displayuserinfo.setForeground(new java.awt.Color(102, 0, 102));
        ta_displayuserinfo.setRows(5);
        ta_displayuserinfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jScrollPane6.setViewportView(ta_displayuserinfo);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 540, 220));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dunyanin-en-guzel-kutuphaneleri.jpeg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 730));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1430, 790));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAddBook.setBackground(new java.awt.Color(255, 255, 255));
        jbAddBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAddBook.setForeground(new java.awt.Color(51, 0, 51));
        jbAddBook.setText("Get Book");
        jbAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddBookActionPerformed(evt);
            }
        });
        jPanel2.add(jbAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 109, 34));

        jbRemoveBook.setBackground(new java.awt.Color(255, 255, 255));
        jbRemoveBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbRemoveBook.setForeground(new java.awt.Color(51, 0, 51));
        jbRemoveBook.setText("Return Book");
        jbRemoveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveBookActionPerformed(evt);
            }
        });
        jPanel2.add(jbRemoveBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 110, 39));

        jbViewBooks.setBackground(new java.awt.Color(255, 255, 255));
        jbViewBooks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbViewBooks.setForeground(new java.awt.Color(51, 0, 51));
        jbViewBooks.setText("View Books");
        jbViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbViewBooksActionPerformed(evt);
            }
        });
        jPanel2.add(jbViewBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 109, 45));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 109, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MAIN MENU");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddBookActionPerformed
        allBooks.setVisible(true);
     
    }//GEN-LAST:event_jbAddBookActionPerformed

    private void addToUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToUserActionPerformed
        String id = searchedId.getText();
        Books book = bookAction.searchBook(Integer.parseInt(id));
        User.getMyBooks().add(book);
        message1.setText("Your book is added!");
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date currentDate = new Date();
        Calendar gettingDate;
        
        message3.setText("Current date: " + sdf.format(currentDate));
        
        Calendar c = Calendar.getInstance();
        c.setTime(currentDate);
        
        c.add(Calendar.DATE, 15);
        
        Date returningDate = c.getTime();
        
        message4.setText("Returning date: " + sdf.format(returningDate));
        
        
        
        
        
       
        
        
    }//GEN-LAST:event_addToUserActionPerformed

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        String id = searchedId.getText();
        Books book = bookAction.searchBook(Integer.parseInt(id));
        searchedBookInfo.setText(book.toString());
                
    }//GEN-LAST:event_jbSearchActionPerformed

    private void jbRemoveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoveBookActionPerformed
        removingBook.setVisible(true);
       
        
    }//GEN-LAST:event_jbRemoveBookActionPerformed

    private void jbViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbViewBooksActionPerformed
        panel_view.setVisible(true);
        int index = 0;
       
        DefaultTableModel model1 = (DefaultTableModel)table_displayAllBooks.getModel();
        
        model1.setRowCount(0);
      
        while (BookAction.book.size() > index) {
           model1.addRow(new Object[]{BookAction.book.get(index).getBookId(),
               BookAction.book.get(index).getBookName(),BookAction.book.get(index).getAuthor(),
               BookAction.book.get(index).getPublisher(),BookAction.book.get(index).getYearOfPublication()}); 
           index++;
        }
       
    }//GEN-LAST:event_jbViewBooksActionPerformed

    private void bt_displayMyBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_displayMyBooksActionPerformed
         int index = 0;
       
        DefaultTableModel model2 = (DefaultTableModel)table_displayMyBook.getModel();
        
        model2.setRowCount(0);
      
        while (User.getMyBooks().size() > index) {
           model2.addRow(new Object[]{User.getMyBooks().get(index).getBookId(),
               User.getMyBooks().get(index).getBookName(),User.getMyBooks().get(index).getAuthor(),
               User.getMyBooks().get(index).getPublisher(),User.getMyBooks().get(index).getYearOfPublication()}); 
           index++;
        }
    }//GEN-LAST:event_bt_displayMyBooksActionPerformed

    private void bt_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_returnActionPerformed
       Menu  qr_mes = new Menu(); 
       qr_mes.setVisible(true);
      message2.setVisible(false);
    }//GEN-LAST:event_bt_returnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           this.setVisible(false);
           Login log = new Login();
           log.setVisible(true);
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_sortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sortingActionPerformed
        ta_alphSorting.setText(bookAction.alphabeticalSorting());
    }//GEN-LAST:event_bt_sortingActionPerformed

    private void CloseViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseViewActionPerformed
        // TODO add your handling code here:
        panel_view.setVisible(false);
    }//GEN-LAST:event_CloseViewActionPerformed

    private void CloseGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseGetActionPerformed
        // TODO add your handling code here:
        allBooks.setVisible(false);
    }//GEN-LAST:event_CloseGetActionPerformed

    private void CloseReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseReturnActionPerformed
        // TODO add your handling code here:
        removingBook.setVisible(false);
    }//GEN-LAST:event_CloseReturnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        message2.setVisible(true);
        if(!bookAction.searchBook(Menu.id).equals(Menu.rb))
        {
            message2.setText("WRONG QR CODE!!!");
        }
            
        if(User.getMyBooks().remove(Menu.rb)){
          message2.setText("Book is returned!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseGet;
    private javax.swing.JButton CloseReturn;
    private javax.swing.JButton CloseView;
    private javax.swing.JButton addToUser;
    private javax.swing.JPanel allBooks;
    private javax.swing.JButton bt_displayMyBooks;
    private javax.swing.JButton bt_return;
    private javax.swing.JButton bt_sorting;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbAddBook;
    private javax.swing.JButton jbRemoveBook;
    private javax.swing.JButton jbSearch;
    private javax.swing.JButton jbViewBooks;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JLabel message1;
    private javax.swing.JLabel message2;
    private javax.swing.JLabel message3;
    private javax.swing.JLabel message4;
    private javax.swing.JPanel panel_view;
    private javax.swing.JLabel remember;
    private javax.swing.JPanel removingBook;
    private javax.swing.JTextArea searchedBookInfo;
    private javax.swing.JTextField searchedId;
    private javax.swing.JTextArea ta_alphSorting;
    private javax.swing.JTextArea ta_displayuserinfo;
    private javax.swing.JTable table_displayAllBooks;
    private javax.swing.JTable table_displayMyBook;
    // End of variables declaration//GEN-END:variables
}
