
import User.User;
import User.Academician;
import User.Student;
import java.awt.event.KeyEvent;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
       
        initComponents();
        adminpanel.setVisible(false);
        wrongAdminpass.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUserId = new javax.swing.JTextField();
        jbLogin = new javax.swing.JButton();
        jbSignUp = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        administer = new javax.swing.JButton();
        adminpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adminpass = new javax.swing.JPasswordField();
        tfPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        wrongAdminpass = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UserId:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 63, 83, 24));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 98, 62, -1));
        jPanel1.add(tfUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 63, 168, 24));

        jbLogin.setBackground(new java.awt.Color(255, 255, 255));
        jbLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(102, 0, 102));
        jbLogin.setText("Login");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 145, 81, -1));

        jbSignUp.setBackground(new java.awt.Color(255, 255, 255));
        jbSignUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSignUp.setForeground(new java.awt.Color(102, 0, 102));
        jbSignUp.setText("Sign up");
        jbSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(jbSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 145, -1, -1));

        message.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 206, 137, 53));

        administer.setBackground(new java.awt.Color(255, 255, 255));
        administer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        administer.setForeground(new java.awt.Color(102, 0, 102));
        administer.setText("Administer");
        administer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administerActionPerformed(evt);
            }
        });
        jPanel1.add(administer, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 234, -1, -1));

        adminpanel.setBackground(new java.awt.Color(255, 153, 51));
        adminpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        adminpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpassActionPerformed(evt);
            }
        });
        adminpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminpassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout adminpanelLayout = new javax.swing.GroupLayout(adminpanel);
        adminpanel.setLayout(adminpanelLayout);
        adminpanelLayout.setHorizontalGroup(
            adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminpass, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        adminpanelLayout.setVerticalGroup(
            adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(adminpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 240, 80));
        jPanel1.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 98, 168, -1));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, 160));

        wrongAdminpass.setBackground(new java.awt.Color(255, 204, 204));
        wrongAdminpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wrongAdminpass.setForeground(new java.awt.Color(255, 255, 255));
        wrongAdminpass.setText("WRONG PASSWORD! Please try again!");
        jPanel1.add(wrongAdminpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 280, 41));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lib.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSignUpActionPerformed

        setVisible(false);
        Signup signup=new Signup();
        signup.setVisible(true);
    }//GEN-LAST:event_jbSignUpActionPerformed

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        // TODO add your handling code here:
        String id = tfUserId.getText();
        int id2= Integer.parseInt(id);
        User.currentId=id2;
       String password= String.valueOf(tfPassword.getPassword());
        
        
       if (User.searchUser(id2, password)) {
            
            LoadingScreen loadingScreen = new LoadingScreen();
            loadingScreen.setUpLoading();
            loadingScreen.setVisible(true);
            this.setVisible(false);
        }
        else{
            message.setText("Please try again!");
            tfUserId.setText("");
            tfPassword.setText("");
            id = tfUserId.getText();
            id2= Integer.parseInt(id);
            password= String.valueOf(tfPassword.getPassword());
           
            if (User.searchUser(id2, password)) {
              setVisible(false);
              LoadingScreen loadingScreen = new LoadingScreen();
              loadingScreen.setUpLoading();
              loadingScreen.setVisible(true);
            
            }
        }
          
        

    }//GEN-LAST:event_jbLoginActionPerformed

    private void administerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administerActionPerformed
      adminpanel.setVisible(true);
      
      
    }//GEN-LAST:event_administerActionPerformed

    private void adminpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminpassActionPerformed

    private void adminpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminpassKeyPressed
          Admin admin= new Admin();
          
          
        if(evt.getKeyCode() == KeyEvent.VK_ENTER ){
                String password= String.valueOf(adminpass.getPassword());
                if (password.equals("winwin2018")) {
                    admin.setVisible(true);
                    this.setVisible(false); 
                }
                else{
                    adminpanel.setVisible(false);
                    wrongAdminpass.setVisible(true);
                    adminpass.setText("");
                }
       }
       
    }//GEN-LAST:event_adminpassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administer;
    private javax.swing.JPanel adminpanel;
    private javax.swing.JPasswordField adminpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbLogin;
    private javax.swing.JButton jbSignUp;
    private javax.swing.JLabel message;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUserId;
    private javax.swing.JLabel wrongAdminpass;
    // End of variables declaration//GEN-END:variables
}
